Add resource function type definition
miragejs/miragejs pull request #1059
Opened 2022-09-22 18:53 UTC by morganmspencer

Adds the resource function type definition to the Server class

2022-09-22 18:57 UTC, cah-brian-gantzler commented
Hoping @IanVS can look at this. I am not using typescript yet

2022-09-22 19:11 UTC, IanVS requested changes
Thanks for the PR!  I made a few suggestions to help narrow down the typing a bit, and would you mind adding a test in https://github.com/miragejs/miragejs/blob/master/types/tests/server-test.ts as well?

2022-09-22 19:11 UTC, IanVS commented on types/index.d.ts
> +    except?: string[];
We can be a bit more helpful here, and use a union of the allowed values.

The values allowed are `'index' | 'show' | 'create' | 'update' | 'delete'`

2022-09-22 19:11 UTC, IanVS commented on types/index.d.ts
> +    resource(model: string, options?: ResourceOptions): void;
Let's restrict the modelName to valid values, like what's done in `createList` above.  

```suggestion
    resource<K extends keyof Registry>(modelName: K, options?: ResourceOptions): void;
```

2022-10-25 20:29 UTC, IanVS approved these changes

2022-10-25 20:29 UTC, merged